language: ruby
sudo: false
rvm:
  - 1.9
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install:
  - gem update bundler
notifications:
  email:
    - ogataken@gmail.com
branches:
  only:
    - master
